CREATE TABLE [dbo].[Order] (
    [ID]                   NVARCHAR (128)  NOT NULL,
    [UserID]               NVARCHAR (128)  NOT NULL,
    [InvoiceNumber]        NVARCHAR (20)   NULL,
    [OrderDate]            DATETIME        NOT NULL,
    [FirstName]            NVARCHAR (50)   NOT NULL,
    [LastName]             NVARCHAR (50)   NOT NULL,
    [ShippingAddress]      NVARCHAR (70)   NOT NULL,
    [ShippingAddress2]     NVARCHAR (70)   NULL,
    [ShippingCity]         NVARCHAR (40)   NOT NULL,
    [ShippingState]        NVARCHAR (40)   NULL,
    [ShippingZip]          NVARCHAR (30)   NOT NULL,
    [ShippingCountry]      NVARCHAR (50)   NOT NULL,
    [BillingAddress]       NVARCHAR (70)   NOT NULL,
    [BillingAddress2]      NVARCHAR (70)   NULL,
    [BillingCity]          NVARCHAR (40)   NOT NULL,
    [BillingState]         NVARCHAR (40)   NOT NULL,
    [BillingZip]           NVARCHAR (30)   NOT NULL,
    [BillingCountry]       NVARCHAR (50)   NOT NULL,
    [Phone]                NVARCHAR (30)   NULL,
    [Email]                NVARCHAR (255)  NOT NULL,
    [Total]                DECIMAL (18, 2) NOT NULL,
    [CCNumber]             NVARCHAR (100)  NULL,
    [CCExp]                NVARCHAR (10)   NULL,
    [CCCardCode]           NVARCHAR (10)   NULL,
    [CCAmount]             DECIMAL (18, 2) NULL,
    [TrxDescription]       NVARCHAR (MAX)  NULL,
    [TrxApproved]          BIT             NOT NULL,
    [TrxAuthorizationCode] NVARCHAR (100)  NULL,
    [TrxMessage]           NVARCHAR (MAX)  NULL,
    [TrxResponseCode]      NVARCHAR (10)   NULL,
    [TrxID]                NVARCHAR (50)   NULL,
    CONSTRAINT [PK_dbo.Order] PRIMARY KEY CLUSTERED ([ID] ASC)
);

